# Generated by Django 5.0.1 on 2024-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(default=2)),
                ('email', models.EmailField(default='shubham10@gmail.com', max_length=254)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
